# Generated by Django 2.2.8 on 2020-05-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeAttendance', '0005_strangerdetails'),
        ('guestmanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_time', models.CharField(max_length=200)),
                ('temperature', models.CharField(default='', max_length=100)),
                ('GuestDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guestmanagementapp.GuestDetails')),
                ('capture_location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='timeAttendance.TerminalDetails')),
            ],
        ),
    ]
