# Generated by Django 2.2.8 on 2020-05-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestmanagementapp', '0002_guestattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestdetails',
            name='valid_until',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
