# Generated by Django 2.2.8 on 2020-05-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestmanagementapp', '0003_guestdetails_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdetails',
            name='nric',
            field=models.IntegerField(unique=True),
        ),
    ]
