# Generated by Django 2.2.8 on 2020-04-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeAttendance', '0003_auto_20190929_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='temperature',
            field=models.CharField(default='', max_length=100),
        ),
    ]
