# Generated by Django 2.2.8 on 2020-05-04 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeAttendance', '0004_employeeattendance_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrangerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_time', models.CharField(max_length=200)),
                ('temperature', models.CharField(default='', max_length=100)),
                ('image_name', models.CharField(max_length=500)),
                ('capture_location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='timeAttendance.TerminalDetails')),
            ],
        ),
    ]
