# Generated by Django 2.2.8 on 2020-07-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeAttendance', '0005_strangerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
