# Generated by Django 2.2.8 on 2021-04-11 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeAttendance', '0007_auto_20210411_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='department2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='timeAttendance.Departments'),
        ),
    ]
